export type Language = 'en' | 'he'

export const DEFAULT_LIST_NAME: Record<Language, string> = {
  en: 'Our Family List',
  he: 'רשימת המשפחה שלנו',
}

export const textByLanguage = {
  en: {
    appTitle: 'Family Shopping List',
    createDescription:
      'Create a family list or join with an invite code. Syncs in real time.',
    createTab: 'Create',
    joinTab: 'Join',
    language: 'עברית',
    yourName: 'Your name',
    yourNamePlaceholder: 'e.g. Avi',
    familyListName: 'Family list name',
    listNameOptional: 'List name (optional)',
    listNamePlaceholder: 'e.g. Katz Family',
    inviteCode: 'Invite code',
    createButton: 'Create Family List',
    joinButton: 'Join Family List',
    joinFallbackListName: 'Family Shopping List',
    welcome: 'Welcome',
    syncDescription: 'This list syncs in real time.',
    youOnly: 'You only',
    membersConnected: 'members',
    cloud: 'Cloud sync',
    inviteCodePrefix: 'Invite code:',
    shareToJoin: 'Share to let family members join.',
    copied: 'Copied',
    copyCode: 'Copy code',
    copyLink: 'Copy link',
    addItemPlaceholder: 'Add an item (milk, eggs, bread...)',
    add: 'Add',
    noItems: 'No items yet. Add your first item.',
    deleteItem: 'Delete item',
    renamePlaceholder: 'Rename this list',
    rename: 'Rename',
    addToHomescreen: 'Add to homescreen',
    installBannerTitle: 'Install the app',
    installBannerDescription: 'Add to your home screen for quick access and offline support.',
    installBannerAction: 'Install',
    buyMeCoffee: 'Buy me coffee',
    coffeePromptTitle: 'Enjoying the app?',
    coffeePromptDescription: 'If this list helped your family shop easier, support it with a coffee.',
    coffeePromptLater: 'Maybe later',
    linkCopied: 'Link copied',
    share: 'Share',
    leaveList: 'Leave list',
    noBackend: 'Centralized backend on Supabase with secure row-level permissions.',
    missingEnv: 'Supabase config is missing. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.',
    loading: 'Connecting...',
    joinFailed: 'Could not join this list. Check invite code.',
    saveFailed: 'Could not save changes. Try again.',
    offlineQueued: 'Offline mode: changes are queued and will sync when online.',
    authFailed: 'Could not authenticate. Check network and refresh.',
    authSetup:
      'Auth setup issue: enable Anonymous sign-ins in Supabase Auth providers, or disable email confirmation for guest email fallback.',
    retryAuth: 'Retry authentication',
  },
  he: {
    appTitle: 'רשימת קניות משפחתית',
    createDescription:
      'צרו רשימה משפחתית חדשה או הצטרפו עם קוד הזמנה. מסתנכרן בזמן אמת.',
    createTab: 'יצירה',
    joinTab: 'הצטרפות',
    language: 'English',
    yourName: 'השם שלך',
    yourNamePlaceholder: 'למשל: אבי',
    familyListName: 'שם הרשימה המשפחתית',
    listNameOptional: 'שם הרשימה (אופציונלי)',
    listNamePlaceholder: 'למשל: משפחת כץ',
    inviteCode: 'קוד הזמנה',
    createButton: 'יצירת רשימה משפחתית',
    joinButton: 'הצטרפות לרשימה משפחתית',
    joinFallbackListName: 'רשימת קניות משפחתית',
    welcome: 'שלום',
    syncDescription: 'הרשימה מסונכרנת בזמן אמת.',
    youOnly: 'רק את/ה',
    membersConnected: 'חברים',
    cloud: 'סנכרון ענן',
    inviteCodePrefix: 'קוד הזמנה:',
    shareToJoin: 'שתפו כדי לאפשר לבני המשפחה להצטרף.',
    copied: 'הועתק',
    copyCode: 'העתקת קוד',
    copyLink: 'העתקת קישור',
    addItemPlaceholder: 'הוסיפו פריט (חלב, ביצים, לחם...)',
    add: 'הוספה',
    noItems: 'עדיין אין פריטים. הוסיפו את הפריט הראשון.',
    deleteItem: 'מחיקת פריט',
    renamePlaceholder: 'שינוי שם הרשימה',
    rename: 'שינוי שם',
    addToHomescreen: 'הוספה למסך הבית',
    installBannerTitle: 'התקינו את האפליקציה',
    installBannerDescription: 'הוסיפו למסך הבית לגישה מהירה ותמיכה אופליין.',
    installBannerAction: 'התקנה',
    buyMeCoffee: 'קנו לי קפה',
    coffeePromptTitle: 'נהנים מהאפליקציה?',
    coffeePromptDescription: 'אם הרשימה עזרה למשפחה לקנות בקלות, אפשר לפרגן בקפה.',
    coffeePromptLater: 'אולי אחר כך',
    linkCopied: 'הקישור הועתק',
    share: 'שיתוף',
    leaveList: 'עזיבת הרשימה',
    noBackend: 'שרת מרכזי על Supabase עם הרשאות שורה מאובטחות.',
    missingEnv: 'חסרה הגדרת Supabase. יש להוסיף VITE_SUPABASE_URL ו-VITE_SUPABASE_ANON_KEY.',
    loading: 'מתחבר...',
    joinFailed: 'לא ניתן להצטרף לרשימה. בדקו את קוד ההזמנה.',
    saveFailed: 'שמירת השינויים נכשלה. נסו שוב.',
    offlineQueued: 'מצב אופליין: השינויים נשמרו וייסונכרנו כשחוזרים לאונליין.',
    authFailed: 'ההתחברות נכשלה. בדקו רשת ורעננו את העמוד.',
    authSetup:
      'בעיית הגדרת אימות: הפעילו Anonymous sign-ins ב-Supabase Auth, או בטלו אימות אימייל עבור מסלול אורח מבוסס אימייל.',
    retryAuth: 'ניסיון התחברות מחדש',
  },
} as const

export type CopyText = {
  [K in keyof (typeof textByLanguage)['en']]: string
}
